name: defiot
description: IoT security evaluation app to scan for vulnerabilities and generate reports
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # State management
  provider: ^6.0.5

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2

  # Local storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0

  # UI components
  fl_chart: ^0.63.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1

  # Other utilities
  uuid: ^3.0.7
  equatable: ^2.0.5
  logger: ^1.4.0
  connectivity_plus: ^4.0.2
  open_file: ^3.3.2
  universal_html: ^2.2.4
  image_picker: ^1.0.2
  flutter_local_notifications: ^15.1.0+1
  url_launcher: ^6.1.12

  # Charts & Graphs
  syncfusion_flutter_charts: ^22.2.9

  # Testing
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#6A40B8"
    theme_color: "#6A40B8"

flutter_native_splash:
  color: "#6A40B8"
  image: assets/images/splash_logo.png
  branding: assets/images/branding.png
  color_dark: "#121212"
  image_dark: assets/images/splash_logo.png
  branding_dark: assets/images/branding.png

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#6A40B8"
    image_dark: assets/images/splash_logo.png
    icon_background_color_dark: "#121212"

  web: false